orbis: 
  email: ""
  password: ""
  urls:
    access: "https://login.eaccess.ub.tum.de/login?qurl=https://dbis.uni-regensburg.de%2fwarpto.php%3fbib_id%3dtum%26color%3d16%26titel_id%3d12630%26url%3dhttps%253A%2f%2forbis4.bvdinfo.com%2fip%2520"
    batch: "https://orbis-bvdinfo-com.eaccess.ub.tum.de/version-20221117/Orbis/1/Companies/BatchSearch/Start"
    logout: "https://orbis-bvdinfo-com.eaccess.ub.tum.de/version-20221117/Orbis/1/Companies/Login/LogOut/ext?setLanguage=en"
    
selenium:
  executable_path: ""
  driver_options:
    - "--headless"
    - "--detach"
data: 
  path: "data/"
  file: "d.csv"
