name: website

# build the documentation whenever there are new commits on main
on:
  push:
    paths:
      - '**.py'
    # Alternative: only build for tags.
    # tags:
    #   - '*'

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: "pip"

      - run: pip install pdoc

      - run: pip install -r requirements.txt
      - run: PYTHONPATH=. pdoc -o docs/ orbi/

      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 051a664b6faf179bb281cbc9c4725bcc
          projectName: orbi
          directory: docs/
          # Optional: Enable this if you want to have GitHub Deployments triggered
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     pages: write
  #     id-token: write
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   steps:
  #     - id: deployment
  #       uses: actions/deploy-pages@v1